server:
  port: 8002
logging:
  level:
    com.fengjx.hello: debug
    org.springframework.cloud.config: debug
    org.springframework.jdbc.core.JdbcTemplate: debug
    org.springframework.jdbc.core.StatementCreatorUtils: Trace

spring:
  profiles:
    active: jdbc,test
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT `KEY`, `VALUE` from app_config where application=? and profile=? and label=?
management:
  endpoints:
    web:
      exposure:
        include: "*"

